apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ganaches.brickblock.io
spec:
  group: brickblock.io
  version: v1alpha1
  names:
    kind: Ganache
    plural: ganaches
  scope: Namespaced
  subresources:
    status: {}
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required:
            - host
          properties:
            host:
              type: string
