apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{metadata.name}}"
  namespace: "{{metadata.namespace}}"
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - "{{spec.host}}"
      secretName: "{{metadata.name}}-tls"
  rules:
    - host: "{{spec.host}}"
      http:
        paths:
          - backend:
              serviceName: "{{metadata.name}}"
              servicePort: 8545
